version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: 'Postgres_for_project_job'
    environment:
      POSTGRES_DB: "DBForJob"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Griffith"
    ports:
      - "5433:5431"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"